package uz.saidoff.crmecosystem.enums;

public enum Permissions {
    GET_USER,
    EDIT_USER,
    DELETE_USER,
    CREATE_USER,
    GET_INTERN,
    READ_INTERN,
    UPDATE_INTERN,
    CREATE_INTERN,

    CREATE_STUDENT,
    GET_STUDENT,
    EDIT_STUDENT,
    DELETE_STUDENT,

    CREATE_CATEGORY,
    DELETE_CATEGORY,
    GET_CATEGORY,
    UPDATE_CATEGORY,

    CREATE_TRANSACTION,
    DELETE_TRANSACTION,
    UPDATE_TRANSACTION,
    GET_TRANSACTION,

    CREATE_OUTCOME,
    EDIT_OUTCOME,
    DELETE_OUTCOME,
    GET_OUTCOME,


    GET_ROLE,
    ADD_ROLE,
    UPDATE_ROLE,
    DELETE_ROLE,


    CREATE_PROJECT,
    DELETE_PROJECT,
    GET_PROJECT,
    UPDATE_PROJECT,

    CREATE_TASK,
    DELETE_TASK,
    UPDATE_TASK,
    GET_TASK,


    //****************ROOMS*****************//
    ADD_ROOM,
    UPDATE_ROOM,
    DELETE_ROOM,
    GET_ROOM,
    GET_ALL_ROOMS,
    ASSIGN_ROOM,
    UPDATE_ASSIGN_ROOM,
    GET_GROUPS_IN_ROOM,



    //**************EQUIPMENTS***************//
    ADD_EQUIPMENT,
    UPDATE_EQUIPMENT,
    GET_EQUIPMENT,
    GET_ALL_EXIST_EQUIPMENTS,
    GET_ALL_EQUIPMENTS,
    GET_ALL_DELETED_EQUIPMENTS,
    DELETE_EQUIPMENT

}
