version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-crm
    environment:
      POSTGRES_DB: crm_ecosystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Root123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/crm_ecosystem
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Root123
    ports:
      - "8080:8080"

volumes:
  postgres_data:
