package uz.saidoff.crmecosystem.util;

public interface MessageKey {

    String THIS_FIELD_CANNOT_BE_NULL = "THIS_FIELD_CANNOT_BE_NULL";
    String USER_ALREADY_REGISTERED = "USER_ALREADY_REGISTERED";
    String NO_CONTENT = "NO_CONTENT";
    String OTP_GENERATOR_NOT_WORKING = "OTP_GENERATOR_NOT_WORKING";
    String OTP_NOT_MATCHED = "OTP_NOT_MATCHED";
    String USER_NOT_FOUND = "USER_NOT_FOUND";
    String SENDING_EMAIL_ERROR = "SENDING_EMAIL_ERROR";
    String OTP_FOR_VERIFICATION_EMAIL = "OTP_FOR_VERIFICATION_EMAIL";
    String SENDING_OTP_SUCCESSFUL = "SENDING_OTP_SUCCESSFUL";
    String BAD_CREDENTIALS_EXCEPTION = "BAD_CREDENTIALS_EXCEPTION";
    String ROLE_NOT_FOUND = "ROLE_NOT_FOUND";
    String ROLE_ALREADY_EXIST = "ROLE_ALREADY_EXIST";
    String USERNAME_NOT_FOUND = "USERNAME_NOT_FOUND";
    String EXPIRED_TOKEN = "EXPIRED_TOKEN";
    String SHOULD_NOT_BE_EMPTY = "SHOULD_NOT_BE_EMPTY";
    String PHONE_NUMBER_ALREADY_USED = "PHONE_NUMBER_ALREADY_USED";
    String NULL_USERNAME_FROM_TOKEN = "NULL_USERNAME_FROM_TOKEN";
    String INVALID_TOKEN = "INVALID_TOKEN";
    String FORBIDDEN = "FORBIDDEN";
    String NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND";
    String GROUP_NOT_FOUND = "GROUP_NOT_FOUND";
    String PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND";
}
